### ISSUE TITLE
Updating to include new ward maps for Chicago

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapgeo#8]
With the pending mayoral and aldermanic election in Chicago, it will soon be time for the official ward map to be replaced with the new version.

My proposal would be to swap out the shapefile when they become official, so, on inauguration of the new council. We could maintain the old files as a reference. @EthanJantz, curious if you have any perspective there. And @nmpeterson  if you have thoughts from afar, would welcome them!

**Comment by nmpeterson** [comment]
You could do [what I did](https://github.com/CMAP-REPOS/cmapgeo/releases/tag/v0.2.0) with the Census geographies when I updated them from the 2010 to 2020 boundaries: rename the existing wards data to `ward_sf_2015` and add the new wards as `ward_sf` in the same pull request. It took me more time to make sure all of the documentation was updated correctly than actually updating the data. (I think my original intention with the `*_2010` datasets was to remove them from the repo once the Census Bureau began releasing ACS 1-year and 5-year data for the 2020 geographies, which they hadn't yet done when I added the 2020 geographies to the repo. In the interest of keeping the package relatively lightweight, you could consider removing the historical versions now.) 

On an somewhat-related note, the Census Bureau released the 2022 vintage of all of their geographies back in September, so you may want to update all of those with `data-raw/load_census_api.R`, too. One big change is the PUMAs, whose 2020 boundaries were not yet officially available when I did the last update -- I left a note about this in the [`puma_sf` docs](https://cmap-repos.github.io/cmapgeo/reference/puma_sf.html). The legislative districts -- [`congress_sf`](https://cmap-repos.github.io/cmapgeo/reference/congress_sf.html), [`ilga_senate_sf`](https://cmap-repos.github.io/cmapgeo/reference/ilga_senate_sf.html), [`ilga_house_sf`](https://cmap-repos.github.io/cmapgeo/reference/ilga_house_sf.html) -- are in a similar position.
