### ISSUE TITLE
Broken CMAP logo on pkgdown

### ISSUE THREAD

**Issue by nmpeterson** [CMAP-REPOS/cmapgeo#9]
I recently purged a lot of stuff in my GitHub Gists, but it turns out one of the Gists I deleted was still being referenced by the cmapgeo (and cmapplot) pkgdown HTML, where the CMAP author text is supposed to be replaced by the logo.

![image](https://user-images.githubusercontent.com/4383272/217623895-f267b4b9-6c89-4715-91bd-3264259d53a1.png)

I don't have a way to restore the Gist with the same URL it used to have (and it probably shouldn't be linked to my GitHub account anymore, anyway). However, here is the SVG image that was used:

![cmap_logo_long](https://user-images.githubusercontent.com/4383272/217624146-e9e0cf5b-b702-4595-8368-a0a117e01b68.svg)

If you save that image somewhere and replace the image URL in `pkgdown/_pkgdown.yml` on both cmapgeo and cmapplot, that should fix the issue. (You might even be able to use the URL of the image I uploaded for this issue -- `https://user-images.githubusercontent.com/4383272/217624146-e9e0cf5b-b702-4595-8368-a0a117e01b68.svg` (assuming GitHub doesn't ever remove images from old issues).

**Comment by dlcomeaux** [comment]
Thanks for flagging this @nmpeterson . I'll upload the image within the repo so that it doesn't live within a personal account. Is there any reason that wouldn't work and that it needs to be in a separate gist?

**Comment by nmpeterson** [comment]
I can't remember why I didn't put it in the repo directly, but I think (hope) there was a good reason. Maybe something to do with the fact that the image substitution requires hardcoded HTML and needs a persistent image URL? There's definitely no reason it needs to be a Gist, specifically.

**Comment by dlcomeaux** [comment]
Hmm, well, for the moment, I was able to do it successfully with a location in the repo. I'll leave it there for now - I was able to extract what appears to be a stable link.
